name: checks

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main

jobs:
  lint:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: lts/*
      - run: corepack enable
      - run: yarn install
      - run: yarn check
      - run: yarn lint

  test-node:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
    name: Test on Node.js v${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 20.x, 21.x]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable
      - run: yarn install
        env:
          YARN_IGNORE_NODE: true # TODO remove after dropping support for Node.js 16
      - run: yarn test
        env:
          FORCE_COLOR: true
          YARN_IGNORE_NODE: true # TODO remove after dropping support for Node.js 16

  test-os:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
    name: Test on ${{ matrix.os }} using Node.js LTS
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: lts/*
      - run: corepack enable
      - run: yarn install
      - run: yarn test

  test-coverage:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
    name: Test on Ubuntu with coverage using Node.js LTS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: lts/*
      - run: corepack enable
      - run: yarn install
      - run: yarn test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@e0b68c6749509c5f83f984dd99a76a1c1a231044 # v4
        with:
          directory: "./coverage"
          token: ${{ secrets.CODECOV_TOKEN }}
